version: "3"

services:
  db:
    image: postgres
    container_name: "telegram-bot-postgres"
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: botadmin
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: "telegram-bot-adminer"
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "/opt/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/opt/redis/data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf --requirepass localpass"
